from Helper import *
from generateRookMoves import *
from generateBishopMoves import *

def generateQueenMoves(board,rowNo,columnNo,turn):
    moves = []
    #CHECKING - ALL SQUARES FROM THE CURRENT QUEEN POSITION TO THE TOP OF THE BOARD
    #CHECKING - ALL SQUARES FROM THE CURRENT QUEEN POSITION TO THE BOTTOM OF THE BOARD
    #CHECKING - ALL SQUARES FROM THE CURRENT QUEEN POSITION TO THE LEFT OF THE BOARD
    #CHECKING - ALL SQUARES FROM THE CURRENT QUEEN POSITION TO THE RIGHT OF THE BOARD
    ##ALL THESE ARE MOVES FROM ROOK
    moves.extend(generateRookMoves(board,rowNo,columnNo,turn))

    #CHECKING - ALL SQUARES FROM THE CURRENT QUEEN POSITION TO THE TOP LEFT OF THE BOARD
    #CHECKING - ALL SQUARES FROM THE CURRENT QUEEN POSITION TO THE TOP RIGHT OF THE BOARD
    #CHECKING - ALL SQUARES FROM THE CURRENT QUEEN POSITION TO THE BOTTOM LEFT OF THE BOARD
    #CHECKING - ALL SQUARES FROM THE CURRENT QUEEN POSITION TO THE BOTTOM RIGHT OF THE BOARD
    ##ALL THESE ARE MOVES FROM BISHOP 
    moves.extend(generateBishopMoves(board,rowNo,columnNo,turn))
    return moves
